### ISSUE TITLE
Doesn't support new "module" values like "nodenext" and "node16"

### ISSUE THREAD

**Issue by fabis94** [azu/tsconfig-to-dual-package#11]
```
Error: Non-support module kind: 199
    at getModuleType (file:///home/fabis/Code/speckle/speckle-server/node_modules/tsconfig-to-dual-package/module/tsconfig-to-dual-package.js:75:11)
    at file:///home/fabis/Code/speckle/speckle-server/node_modules/tsconfig-to-dual-package/module/tsconfig-to-dual-package.js:114:23
    at Array.map (<anonymous>)
    at tsconfigToDualPackages (file:///home/fabis/Code/speckle/speckle-server/node_modules/tsconfig-to-dual-package/module/tsconfig-to-dual-package.js:89:54)
    at async Module.run (file:///home/fabis/Code/speckle/speckle-server/node_modules/tsconfig-to-dual-package/module/cli.js:49:5)
```

**Comment by azu** [comment]
https://github.com/azu/tsconfig-to-dual-package/blob/1d5dda612039ce6af81694b95eed20be25f802f2/src/tsconfig-to-dual-package.ts#L81-L89
fmm, this logic is something wrong.


> The emitted JavaScript uses either CommonJS or ES2020 output depending on the file extension and the value of the type setting in the nearest package.json. Module resolution also works differently. You can learn more in the [handbook](https://www.typescriptlang.org/docs/handbook/esm-node.html)
https://www.typescriptlang.org/tsconfig#node16nodenext-nightly-builds

It looks like tsc detect the type via `package.json`'s `type` fields.

**Comment by azu** [comment]
Fixed in https://github.com/azu/tsconfig-to-dual-package/releases/tag/v1.2.0

Please try it!

**Comment by fabis94** [comment]
@azu seems to work, thanks for the quick fix!
